### ISSUE TITLE
object's size is not normal and moving position only rotates the object

### ISSUE THREAD

**Issue by rustylabs** [AryanpurTech/BlueEngine#98]
Using version:

```toml
blue_engine = "0.7.0"
blue_engine_utilities = {version = "0.7.0", features = ["egui"]}
```

https://github.com/user-attachments/assets/29c90c57-4b17-4e51-bdf3-8ec619433af9

Not too sure why the object is not appearing like a square and if you move the object it will make the object rotate weirdly as shown in the video.
